# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, null=True)),
                ('menu_text', models.CharField(max_length=150)),
            ],
        ),
    ]
