# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, null=True)),
                ('menu_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Navigation menu'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_text',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='page_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menu_item')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.Menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('menu.menu_item', models.Model),
        ),
    ]
