# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('menu', '0004_menu_menumenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='internallink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page'),
        ),
    ]
