# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_item_internallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='internallink',
            new_name='internal_link',
        ),
    ]
