# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('menu', '0009_auto_20160621_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='childitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('childtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('childpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='childpage',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='childtitle',
        ),
    ]
