# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('menu', '0010_auto_20160621_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childitem',
            name='childpage',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childpage', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='childitem',
        ),
    ]
