# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('menu', '0011_auto_20160621_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='childtitle',
            new_name='childtitle0',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='childpage',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childpage0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childpage1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childpage2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childpage3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childtitle1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childtitle2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='childtitle3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
