# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20160621_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='childpage0',
            new_name='page_1',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childpage1',
            new_name='page_2',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childpage2',
            new_name='page_3',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childpage3',
            new_name='page_4',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childtitle0',
            new_name='page_title1',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childtitle1',
            new_name='page_title2',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childtitle2',
            new_name='page_title3',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='childtitle3',
            new_name='page_title4',
        ),
    ]
